### ISSUE TITLE
On macOS 10.14 lbxml headers are no longer under /usr/include

### ISSUE THREAD

**Issue by deszip** [AlexDenisov/bitcode_retriever#10]
Unfortunately as stated here:
https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes?language=objc

on 10.14 there are no libxml headers in /usr/include:

`However, some software may fail to build correctly against the SDK and require macOS headers to be installed in the base system under /usr/include. If you are the maintainer of such software, we encourage you to update your project to work with the SDK or file a bug report for issues that are preventing you from doing so.`

Changing include directory to one containing headers (in my case `/opt/local/include/libxml2` ) helps.

Maybe distributing via Homebrew when they'll have a fix will help, they are aware of the issue:
https://github.com/Homebrew/brew/issues/5068

**Comment by AlexDenisov** [comment]
Hi @deszip, thanks a lot for the report.
Unfortunately, I do not maintain this tool actively. I do recommend taking a look at [LibEBC](http://github.com/JDevlieghere/LibEBC) instead.
It does the job better :)
