### ISSUE TITLE
Make script fails on Sierra

### ISSUE THREAD

**Issue by Legoless** [AlexDenisov/bitcode_retriever#7]
I'm trying to build bitcode_retriever, but make command fails:

```
In file included from main.c:2:
./macho_util.h:8:10: fatal error: 'libxml/tree.h' file not found
#include <libxml/tree.h>
         ^
1 error generated.
In file included from macho_util.c:3:
./macho_util.h:8:10: fatal error: 'libxml/tree.h' file not found
#include <libxml/tree.h>
         ^
1 error generated.
make: *** [all] Error 1
```

Obviously `-lxml2` parameter doesn't work correctly here. Any ideas why?

**Comment by JDevlieghere** [comment]
The libxml2 library is shipped with macOS, however the headers are not. Did you use brew to install libxml2? If you did, try `brew link --force libxml2` to put them in the system include directory.

**Comment by Legoless** [comment]
I did not install it with brew, but I tried doing that and also linking them with command you pasted. It does not solve the problem though.

**Comment by JDevlieghere** [comment]
Hmm, that's odd. Can you check whether `/usr/include/libxml2/libxml` exists?

**Comment by Legoless** [comment]
Yes, it does exist. Could it be a permissions issue?

**Comment by JDevlieghere** [comment]
I've updated the makefile to explicitly include the libxml2 header path. This should fix the issue. Let me know if it worked for you!

**Comment by AlexDenisov** [comment]
@JDevlieghere indeed, your commit does the trick, thanks a lot for the quick fix.
@Legoless thanks for reporting this issue.

**Comment by Legoless** [comment]
Thank you for fixing this so quickly!
