### ISSUE TITLE
bitcode_retriever -extract does not work

### ISSUE THREAD

**Issue by spinningarrow** [AlexDenisov/bitcode_retriever#9]
When using `bitcode_retriever -extract fat_app` I get the following error:

```
./bitcode_retriever: illegal option -- x
Unknown option `-x'.
```

`--extract` does not work either.

**Comment by spinningarrow** [comment]
Update: `-e` seems to be working (I think).

**Comment by AlexDenisov** [comment]
Yepp, looks like a 'typo' in the README.md.

**Comment by AlexDenisov** [comment]
I update readme, could you confirm that `-e` works for you, @spinningarrow?

**Comment by spinningarrow** [comment]
Perfect, thanks!
